name: checkstyle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Checkstyle
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Env setup
        run: |
          echo "::group::Environment Setup"
          mkdir -p /opt/lib
          wget -q -O /opt/lib/checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.6/checkstyle-10.12.6-all.jar
          cd "${GITHUB_WORKSPACE}"
          echo "::endgroup::"

      - name: Start Checkstyle Group
        run: echo "::group::Running Checkstyle"

      - name: Run Checkstyle
        run: |
          exec java -jar /opt/lib/checkstyle.jar "." -c "checkstyle_checks.xml" -f xml > results.xml

      # Install reviewdog CLI
      - name: Install reviewdog
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh \
            | sh -s -- -b /usr/local/bin

      # Run reviewdog using Checkstyle XML
      - name: Reviewdog (Checkstyle)
        run: |
          reviewdog -f=checkstyle -name="checkstyle" -reporter=github-pr-check < results.xml
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Results (Colorized)
        run: |
          sed -e 's/error/\x1b[31merror\x1b[0m/g' \
              -e 's/warning/\x1b[33mwarning\x1b[0m/g' results.xml

      - name: End Checkstyle Group
        run: echo "::endgroup::"

      - name: Check Results
        run: |
          if grep -q error results.xml; then
            echo "Checkstyle found an error - see the logs above."
            exit 1
          else
            echo "No errors found!"
          fi
